version: '3.8'

volumes:
  postgres_data:
  staticfiles:
  mediafiles:
  nginx_conf:

services:
  db:
    image: postgres:13.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  
  web:
    image: ptnt/foodgram
    container_name: web
    restart: always
    volumes:
      - staticfiles:/foodgram/static
      - mediafiles:/foodgram/media
      - nginx_conf:/foodgram/nginx/ 
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.7-alpine
    container_name: nginx
    restart: always
    volumes:
      - staticfiles:/foodgram/static
      - mediafiles:/foodgram/media
      - nginx_conf:/etc/nginx/conf.d/ 
    ports:
      - "80:80"
    depends_on:
      - web
