# Generated by Django 3.1.7 on 2021-03-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210303_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='fav_counter',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Счетчик добавлений в избранное', null=True, verbose_name='Добавлений в избранное'),
        ),
    ]
