# Generated by Django 3.1.7 on 2021-03-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210310_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин')], help_text='Тег', max_length=10, unique=True, verbose_name='Тег'),
        ),
    ]
