# Generated by Django 3.1.7 on 2021-03-23 10:15

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20210322_1900'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user__exact=django.db.models.expressions.F('author')), name='self_sub_inhibit'),
        ),
    ]
