# Generated by Django 3.1.7 on 2021-03-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20210323_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, help_text='Цвет тега на страницах сайта', max_length=10, verbose_name='Цвет'),
        ),
    ]
